apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "vegfruits-classifier"
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    minReplicas: 1
    # maxReplicas: 3
    # containerConcurrency: 2
    # canaryTrafficPercent: 30
    serviceAccountName: s3-read-only
    pytorch:
      protocolVersion: v1
      storageUri: s3://mybucket-emlo-mumbai/kserve-ig/vegfruits-classifier/
      # storageUri: s3://tsai-emlo/kserve-ig/fakeimagenet-vit/
      # image: pytorch/torchserve-kfs:0.12.0
      image: 306093656765.dkr.ecr.ap-south-1.amazonaws.com/model-onnx-server:latest
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 5200m
          memory: 8Gi
      env:
        - name: TS_DISABLE_TOKEN_AUTHORIZATION
          value: "true"
