FROM python:3.9-slim
USER root

WORKDIR /workspace
RUN mkdir -p /workspace/model
RUN mkdir -p /opt/mount/model
COPY . .
RUN pip3 --no-cache-dir install numpy==1.26.4
RUN pip3 --no-cache-dir install torch==1.12.0+cpu torchvision==0.13.0+cpu -f https://download.pytorch.org/whl/torch_stable.html


CMD ["python", "infer.py"]
