# https://hydra.cc/docs/configure_hydra/intro/

defaults:
  - override /paths: default
  - override /data: dsports
  - override /model: msports
  - override /callbacks: default
  - override /logger: default
  - override /trainer: default
  - override hydra/sweeper: optuna



task_name: "hparams"  #used in hydra-config to write logs
script: false


tags:
  - hparams

hydra:
  mode: "MULTIRUN"  
  launcher:
    # don't go above [RunTimeError:: Please call `iter(combined_loader)` first.]
    # `NOT ABLE to UNDERSTAND :(`:: https://github.com/Lightning-AI/pytorch-lightning/issues/19373 
    # No activity:: https://github.com/openvinotoolkit/anomalib/issues/2078
    # n_jobs: 1  

    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 1
    verbose: 1
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      prior_weight: 1.0
      n_startup_trials: 3
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    storage: null
    study_name: optimal_searching
    n_trials: 2
    n_jobs: 16
    max_failure_rate: 0.0
    params:
      # https://github.com/facebookresearch/hydra/discussions/2906
      model.stem_type: choice('patch','overlap')
          